# Site settings
title: Dyst0rti0n's Cybersecurity & Programming Blog
email: dystorti0n@proton.me
description:  Exploring advancements of cybersecurity, programming, and more.
baseurl: ""
url: "https://dyst0rti0n.github.io" 
github_username:  Dyst0rti0n
author: Dyst0rti0n

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Custom settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title.html

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include custom CSS
sass:
  style: compressed

# Paths to search for Jekyll includes
includes_dir: _includes
layouts_dir: _layouts

# Paths to search for Jekyll data files
data_dir: _data

# Paths to search for Jekyll assets
assets:
  sources:
    - _assets/css
    - _assets/js
    - _assets/images