# Site settings
title: Dystortion's Academy
email: dystorti0n@proton.me
description: Exploring advancements of cybersecurity and programming, whilst providing learning modules.
baseurl: ""
url: "https://blog-site-self.vercel.app/"
github_username: Dyst0rti0n
author: Dyst0rti0n

# Collections
collections:
  newsletters:
    output: true
    permalink: /newsletter/:path/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Custom settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include custom CSS
sass:
  style: compressed

# Paths to search for Jekyll includes
includes_dir: _includes
layouts_dir: _layouts

# Paths to search for Jekyll data files
data_dir: _data

# Paths to search for Jekyll assets
assets:
  sources:
    - assets/css
    - assets/js
    - assets/images

# Navigation settings
navigation:
  - text: "Home"
    url: "/"
  - text: "Blog"
    url: "/blog"
  - text: "Newsletter"
    url: "/newsletter"
  - text: "Learning Academy"
    url: "/academy"
  - text: "Shop"
    url: "/shop"
  - text: "Projects"
    url: "/projects"
  - text: "Apex"
    url: "/apex"
  - text: "Contact"
    url: "/contact"
